language: java
jdk:
  - openjdk6
  - openjdk7
before_script:
env:
  global:
    secure: "lqbF09R11Q83BBQ3vaZu9GYNVqy7Ot1B/jVPVk7Hvik/2G4TvioBuQIQ9XQwSA26SH2OLqfCFn6erAfiB+RzbJdNxhMQVl3YWJimo0iJ0czZ9ZWauydQq39SBM4MMgkcVId2SrtuYKqr7oWuY+Jk6YInPBNiJEW27cYh7luybMlIR41YOKSP7TpU2v8eJr0tfRa5wEqfi6SegG/PL82m9jeIISHMgxqxT3qANOuXeJ0Zc3qtwi90WZWjoiXMGEpEVs5ayfpXRsIZc8AQvnQUchADX8Z/4P4nXV07IZ2iFmQW/3jz5Bh8VzgPbvz0doZQa7d/bs+qqyYUBP3EbItYVxKpMUQSybErDbsHIkyKSVCJTF1d3laOtaBLk48T3hbmjv5alX11UsbDya68IxVZPXs5i+vmfNYSn2v8IbYwo9A1Nu+FcqMkTsdP7byunhTCqh7OESBAimliK1vyYwNnZUq1OUBC876QbxKxhPCeByBYY+p7hThqwYWBzdWJHfNOjHGY/cZ38GqJQIXFAl+PTuQY//2ofSdkbW7ixf4WHbBfdyBwBPKpc6oJSEFkjKa1MXbCuulVXbQdcngu6/im4f8BjYqj7RPe6B58uZ8YO0TPbQs/BogG02sKCumUhKSZYvX3z3KNYdEsV1Dc6uJq2dBZqId8gja2rLArFumBAwU="
script:
  - echo "aaaaaaaaaaaaaa"
  - mvn deploy -X
after_script:
after_success:
after_failure:

