language: java
jdk:
  - openjdk6
  - openjdk7
before_script:
env:
  global:
    secure: "LxV3P8psKiVlGv2DX+OPxvHXMCoWcTgpg3WM6P4123ET4+Wjcu1/ph+j5Dz9BzITzlql39m1jfB819v43VWgvAJ0N1EaZev2ioiUm8ggPQcMB/9dWLV5nydHfxLUakt9CN3j3Q4jt45IMBFgwzqO7FrmcUd0IUuakw4wxydNkEailBLeZ+CNZCdgP7LJP/Wuy0pXDnQNZnz3sTg41YGiU/AfwngX+1QnnGdPSjcSkwbxHila1Lju2dzF/Y2xNL8lXu6+24hzFBjuwyQf2Aktopo6pDYDdswE/0CVKCWjpzPrClFFPulQiGAB3x4OZFBlGMnTPl8HRy1ucQi06n+raNCmnHoya8x8doDkY3hqS/9dlOvyENZehQ5kVP647m8Pvke0tu8NAfBYWoJUUc103E2mosu7Ig8TedqIWNpDuH+cGn//Wohbmap1deiRsGxiMpGs8UkX1tGiIddAV1hZPs//svPddlp2L1hyPbyphY55fW0mO9+6lnElUnJA4NtFWf0nrp48DtT9hv7rrSZtZy9nLSvxLZPNegr+NKFh+j1RQfD8WqY9BGymRL00v234QI+ORTMOYoIZhKRl2GZ0Efquj2ko9vicrBoYAIwYtDgnBrhAKqkB6hnggLFJIjz7/6f2LalYiL5qQaeDQerrR4qkVr3QZYXOwg5l7SllFbU="
script:
  - echo "aaaaaaaaaaaaaa"
  - mvn deploy -X
after_script:
after_success:
after_failure:

