language: java
jdk:
  - openjdk6
  - openjdk7
env:
  global:
    secure: "fd9jkSx0SE28XnfNEH8qbecMMsHvuetkwdOMdAIogvzHzeMYPt/4h4JmwC016+wqCTnXHieNnzH04f6QTfuvackRItpjXO9MXTiIbIB+/NvxV4cxE2oPjbXlzQH8UHgGCt3P7BDQM3DNUuRreYOm6yX+PvjLLNYNu5uhSMB+b/nFz4WY3JsmXpfNUn6nA3vROBvnh/AMW1gvO0/Jpebg+vvSouF1g4jm4/1P4aJ9ewEWyqoeQfEn37zV/y7DGIJgvc0mhr6VpX8h7waeFHXypbwHHog0M5ExSF+lAoXcjKM32ewrPmCgq2jzJq3hA16iJ1V79e45T+mpl9/inmu3EklQpmid7G7FmsgfEZqripRxzfQ+sm/LdcXHQRWXKjQzNkqiRPz7wjSm4/CyunqvgApfL31FUbNZyNOUiSpm+oFMyX6ESks7PkwWNc7PQpOFrOueSat+grhi9TvFG7SifPxufyAwG7J2hrA/rVLD/BwM0eCJkave19nIhV/3k94VDyUzdlYpkhj6mxHePcjfS2Noy6VmDSxwWCTGXMtTp1YpB53WErFZsX6whm0htarge6aqtBXF07BXoarPFXWWET8FHhW4jjudEEmuPJMSnw5H3mwg1DIk7RD8kZjJ0Vaa63Th7FznzuRyr6ErHYsl+OunsJJeeWVYXQUW7yyI53M="
before_script:
script:
  - mvn deploy -X
after_script:
after_success:
after_failure:

