language: java
jdk:
  - openjdk6
  - openjdk7
before_script:
env:
  global:
    secure: "XfO6zkFDiXbQfY7iVjfYx6EFcb0hfYAgLiFvgBwBliaaJ2ukH0DIkrHIzv7ChJOVyhGGJFDVhjgjlj0Iugi3wD7l/tDoBjpzyUpGX8ErY40Zp3cUyZziNlFCAKA7XdKgES5o125z+WsJWUDRZFFZNMT3xlNm1wWC90xpxD6KXb9FqnR29dCc09uskQDuhyecGqN8urYRRmv9cCdCJGuIs0sOvKvHPR8VJqwvB6mLv0lwBd/KyUIGf2gfH0a5EV2Ez/jm0iWH7Q7V6NET+lUHPJmRKhKaywdC043XoStIjpXed0eYHEJGuQEKNuZsiNSm6WcrVsYVP6g4kBJYgXwRdJJIu+lancJKkD6vToMcDqApYNQDfOxQSf0NMddVd2JMDV+Uh6QbCOndeRXOVm5WxWHnXVlbeuUjUlYt/rOfE7P3tOl8iHvtSRf+0j57wIIk3QnhJunhJz//lMG5hDqZ/a2YQxZQnkV8ThGiSRfM5xkewgkdun88XMVNMZ2uY1P+0zBstd7y4BiM+oTyc9zQCbNSZbKNi52toENwi3YC3VWcmnUpsb3QV4Coi59hAQ/1++CIZNTU3rGXlbkpFP7uMBXY/Zu5UkCDNcQbPF2t5CdfBP7e4ZSJJd+7jNAlHwPUwGucRELY6vrDQYc2shtplAJIjbQaMdktRJkWUeL8ZFo="
script:
  - mvn deploy -X
after_script:
after_success:
after_failure:

