language: java
jdk:
  - openjdk6
  - openjdk7
before_script:
env:
  global:
    secure: "i3CL0raH5Lii5qUD9tyOpery41Tpy1N6DtOTI/j4cBgjmfErD2MeKFVxQMXHZmaPt9aF2xk01ICp9BCd+fwPSRQmDkhLSmRPEQZioNDKfnvH6vrJb8uL4ZF8aAzFLkBrWCD2G//8xgeI5rk0T5ADCKgKaUwMCWufj0yOvgsU2FPGB5DdwodKvARBB5tEex60tv5k0+uH4VOtMxJ3XpA6FYZ/hm31iG6dGEYB1n8iWt4ZdHX30P2bi8Y5LCWgkGsmmXpIFSxyqbg0Wnoypjbv5fDDypXytcTRkQoE3DriRalpSc7sRk8VVUbtRAUnB6jnDuDeLX5MXDVlMS1hg2pQ13HR4Mj3R2BVDCXn6qbfs0K/uuvlDFoRhobvUy6gVdmkPxlX5XVMnKNOjK/vtALOo4rGeBwV1J4er8rr2PGr4zDRRSXaXWzdx+AxouhHAxHvl+agXCjheTF402n3nk2Nyp6B15jRF4DcD3XPzlOAy7eJPwOoA/OzYyJnqx2vJdpN88B4JMO6OvsTiYzS1htzeTs7NGPF5YMTL199Oh9i3vJt51nt7L2yu5nQcrnqaa+Snjog5Y6Rufwh+MTi7yfPlDlMlXZKOhtMlCFMLKBuPtfJo3tOiNsAx5/fRSnjw9z9xgJkCDOJAJgODlqDL4yF77pZhHD8eepd5y8+xt+gQeI="
script:
  - echo "aaaaaaaaaaaaaa"
  - mvn deploy -X
after_script:
after_success:
after_failure:

