language: java
jdk:
  - openjdk6
  - openjdk7
before_script:
env:
  global:
    secure: "UU8qcuFNTi+FvmET0y1N1IQS0LtNfzUu6p5I2k2Wj7kyNfz9qAUWbx3iy0femUFZPBpGry1dkQzTDoliq4JRRw1Gn+QedbRS/Xs8EY7V6ixnC8tt0PTFeyIYJvlZh+6H15TeEpt9HZfKcnsY5ET2vwZMeLCBN2gaaVDnkXNVn4FvU1gt2vAd9N/6cPQcr4iK69BsmjtI4JXwFuQYmLjxAwQFe7Bwm9gm1Ysq1n672CGlINKhSs+nD/tYY/opkKOtXwDpEwmsEsFPwN+rg8rrYua76Z78QrexiSU4iRA9/DpH6/HV1hiTwfKV9V/CB/egRZXHz36+88vUkK/XmrU3hUMaShyeXW2WF6hTTvch8hvY0yY9U3fO4Z+78glPidq6xtPY6kNpbgFOeAgHympEMwLHew0MTn2Jn9lBgV4MRtBywbNTQ0Wp2F/OJ83NxnmBJ+c/C9WfyuMwAZToNcud8UCOQCDO99m8frxZFjVH7t+2hO969Y81cYLr+0Y961m1kLURv62KuoocOIj5le+cJ0Id2VrcRauZ0eHOgC3VFN4BnmW7lKtO72R/1mRNFOmZnb+g8U4NZgsuzovB/17T7v7bLwPNlqTDJUqcCeuaM/UwQ69OuRFXRUhxk5bfMpnbfggICEgmELCzfmivoxrCNs4UBfWK6OWJr3XyfGVbNCg="
script:
  - echo "aaaaaaaaaaaaaa"
  - mvn deploy -X
after_script:
after_success:
after_failure:

