language: java
jdk:
  - openjdk6
  - openjdk7
before_script:
env:
  global:
    secure: "EkvouLUc8gP1mR2FKID55u+M91Ldy4tPc6UA23sNT7p/jOOwp9QwiD+5E/SfMBTodSwVxwPBD4GHA95p6cn+8d7rcppm3Fw5C3PkRDgFwINMas7x27iqfdP2FHwIsLXmz1seJmCUzHc8mKA36KvkQVdhbCnU5FoLXczpBE40aVAQfNKIqHdZfVb3VXJEFUxsB26stETbWgNXQR8FByDwPPxfckxqYZrilnroifucrLqHRIHnYJrwQzelNbXM+tgI5yPs5TTUBUMaIFTh85mdH4umTveTdhAitOzst/uGns8bGzp3dukqYdEkc2EbNoTslWvlMXPMICWyhYi9AxZYga2V0xSj7eqOLhKlJWQDIoLvy9zF3MZb8On/ZU5nEVVIAPMiy2tau/j4lMNA2z72G2XZEoyYlluTVXCb49R5lhdHYGLzCHIA1EsUkbf0J7BTmQRXWs4czcispWCEouj8593dTzUxUdTRnYkjV41SsN4AGSqzyLE5PxpJQNCfrJjuw10YONjlA7joOGocvu8lSgjXXXbk/dYgkR+pTz7Y4AZTClTAdEvgFRrSPwOh1I9qxmMW99UoyGM26sJ9+LqgDYXA6AvBI49ntOvitIDtQ2gNPlKYLo2sxni0xDkf0f8QNMqXX3NqUUIP+w9yWpSdyRJRQ8qCltrjv9HQ7FuBej4="
script:
  - echo "aaaaaaaaaaaaaa"
  - mvn deploy -X
after_script:
after_success:
after_failure:

